resolver: lts-6.22
#resolver: lts-7.4

packages:
- '.'

# - ../flat
- location:
   git: https://github.com/tittoassini/flat
   commit: 3ae580d

# - ../model
- location:
   git: https://github.com/tittoassini/model
   commit: 0e1fe4f

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}
