resolver: lts-5.14

packages:
- '.'
- ../flat
- ../model

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}
