resolver: lts-6.30
#resolver: lts-7.20
#resolver: lts-8.5

packages:
- '.'

- location: ../flat
  extra-dep: true

extra-deps:
- model-0.2.4
- timeit-1.0.0.0 
- mono-traversable-1.0.2
#- binary-0.8.5.1
- cryptonite-0.22
